config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
      

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'

  resources :reviews
  resources :meditations do 
    resources :reviews, only: [:new, :index]
  end

  resources :techniques
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meditation.rb
class Meditation < ApplicationRecord
  belongs_to :technique
  belongs_to :user #creator of it
  has_many :reviews
  has_many :users, through: :reviews, :dependent => :destroy 
#have many users who have reviewed a specific meditation through reviews
  accepts_nested_attributes_for :technique

  validates :mood, presence: true
  scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}
  scope :starts_with, -> {where("mood LIKE ?", "A%")}

  # def self.starts_with(a)
  #   self.where("mood LIKE ?", "A%")
  # end

  def self.alpha
    order(:mood)
  end

  def technique_attributes=(attributes)
      self.technique = Technique.find_or_create_by(attributes) if !attributes['name'].empty?
      self.technique
    end


  def technique_name
  technique.try(:name)
  end 

  def mood_and_technique
    "#{mood} - #{technique.name}"
  end
  
 
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :meditation
  
  validates :title, presence: true
  validates :stars, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 6}

  validates :meditation, uniqueness: {scope: :user, message: "has already been reviewed by you"}

 scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}

end

app/models/technique.rb
class Technique < ApplicationRecord
    has_many :meditations

end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :reviewed_meditations, through: :reviews, source: :meditation
    #a user has many reviewed meditations---> and can create reviews on any meditation including their own


    has_many :meditations #referring to a user who has created many meditations

    validates :username, uniqueness: true, presence: true

    has_secure_password 

    def self.create_by_google_omniauth(auth)
       self.find_or_create_by(username: auth[:info][:email]) do |u|
            u.password = SecureRandom.hex
       end
        
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    private
  
    def logged_in?
      !!session[:user_id]
    end
  
    def current_user
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
  
    def redirect_if_not_logged_in
      redirect_to login_path if !logged_in?
    end
  
  
  end

app/controllers/meditations_controller.rb
class MeditationsController < ApplicationController

    before_action :set_meditation, only: [:edit, :update, :destroy]
    before_action :redirect_if_not_logged_in

    def new
        @meditation = Meditation.new
        @meditation.build_technique
    end

    def create 
        @meditation = Meditation.new(meditation_params)
        @meditation.user_id = session[:user_id]
        if @meditation.save
            redirect_to meditation_path(@meditation)

        else 
            render :new
        end
    end
    
    def index
        binding.pry
        if params[:q]
            @meditations = Meditation.starts_with
        else
            @meditations = Meditation.order_by_rating.alpha
        end
    end

    def show
        @meditation = Meditation.find_by_id(params[:id])
    end

    def edit
        @meditation = Meditation.find_by_id(params[:id])
    end

    def update
        @meditation = Meditation.find(params[:id])
    
        if @meditation.update(meditation_params)
          redirect_to @meditation 
        else 
          render 'edit'
        end 
    end

    def destroy
        @meditation.destroy
        redirect_to meditations_path
    end

    private

    def set_meditation
        @meditation = Meditation.find_by_id(params[:id])
    end

    def meditation_params
        params.require(:meditation).permit(:mood, :duration, :technique_id, technique_attributes: [:name, :description])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :redirect_if_not_logged_in

    def index
        if @meditation = Meditation.find_by_id(params[:meditation_id])
            @reviews = @meditation.reviews
        else 
            @reviews = Review.all
        end
    end

    def new 
        if params[:meditation_id] && @meditation = Meditation.find_by_id(params[:meditation_id])
            @review = @meditation.reviews.build
        else 
            @review = Review.new
        end
    end

    def create 
        @review = current_user.reviews.build(review_params)
        if @review.save
            redirect_to review_path(@review)
        else 
            render :new
        end
        
    end

    def show
        @review = Review.find_by_id(params[:id])
    end


    private
    
    def review_params
        params.require(:review).permit(:stars, :title, :content, :meditation_id, meditation_attributes: [:mood, :duration])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def welcome
        
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    def new

    end

    def create
        if params[:provider] ==  'google_oauth2'
            @user = User.create_by_google_omniauth(auth)
    
            session[:user_id] = @user.id
            redirect_to user_path(@user)
       
        else
            @user = User.find_by(username: params[:user][:username])
            
            if @user && @user.authenticate(params[:user][:password])
                session[:user_id] = @user.id
                redirect_to user_path(@user) 
            else
                flash[:error] = "Sorry, please try again. "
                redirect_to login_path
            end

        
        end
    end


    def omniauth
        @user = User.create_by_google_omniauth(auth)
        session[:user_id] = @user.id
        redirect_to user_path(@user) 
    end

    private 

    def auth
        request.env['omniauth.auth']
    end
    

end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
        @techniques = Technique.all

    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
       @user = User.new 
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_nav_bar
      if logged_in?
        render partial: 'layouts/loggedin_links'
      else
        render partial: 'layouts/loggedout_links'
      end
  end

  def alert_class(flash_type)
    case flash_type.to_sym 
    when :notice 
      "alert-success"
    when :alert 
      "alert-warning"
    when :error 
      "alert-danger"
    end
  end

end

app/helpers/meditations_helper.rb
module MeditationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def display_header(review)
        if params[:meditation_id]
            content_tag(:h1, "Add a Review for #{review.meditation.mood} -  #{review.meditation.technique.name}")
        else
          content_tag(:h1, "Create a review")
        end
    end
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger errors">

    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin_links.html.erb
<div class="topnav" id="myTopnav">


<%= link_to "Home", user_path(current_user)%>
<%= link_to "Add a Meditation", new_meditation_path %> |
<%= link_to "All Meditations", meditations_path %> |
<%= link_to "Add a Review", new_review_path %> |
<%= link_to "All Reviews", reviews_path %> |
<%= link_to "All Techniques", techniques_path %> |
<%= link_to "Log Out", logout_path, method: :delete %> |


</div>

app/views/layouts/_loggedout_links.html.erb
<div class="topnav" id="myTopnav">
 <%= link_to "Login", login_path %> 
<%= link_to "Signup", signup_path %> 
<%= link_to "Sign in with Google", '/auth/google_oauth2', method: :post %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeditationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
    <div><%= render_nav_bar %></div>

    <section class="container"> 
    <div id="flash">
    <% flash.each do |key, value| %> 
      <div class="flash alert <%= alert_class(key) %>"><%= value %></div>
    <% end %>
    </div>
  </section>

  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meditations/_form.html.erb
<%= render partial: 'layouts/errors' , locals: {object: @meditation} %>
<%= form_for(@meditation) do |f| %>
<div>
<%= f.label :duration  %>
<%= f.text_field :duration %>
</div>
<br>
<div class="form-group">
Current <%= f.label :Mood %>
<%= f.text_field :mood %>
</div>
<br>
<p> Select a Technique that already exists</p>
<div class="form-group"> 
<%= f.collection_select :technique_id, Technique.all, :id, :name, include_blank: 'Select One' %>
</div>
<br>
<p>Or create a new Technique: </p>
<div class="form-group">
<%= f.fields_for :technique, Technique.new do |p|%>
<%= p.label :name %>
<%= p.text_field :name %>
<%= p.label :description %>
<%= p.text_field :description %>
<% end %>
<br>
</div>
<br>
<%= f.submit %>
<% end %>

app/views/meditations/edit.html.erb
<h1>Edit</h1>

<%= render 'form'%>

app/views/meditations/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}
td, th {
  border: 1px solid #DDDDDD;
  text-align: left;
  padding: 8px;
}
tr:nth-child(even) {
  background-color: #DDDDDD;
}
</style>
</head>
<body>
<div class="meditation-container">
  <h1>All the Meditations</h1>
</div>
<table>
<thead>
  <tr>
    <th>Mood</th>
    <th>Users</th>
    <th>Duration</th>
    <th>Technique</th>
  </tr>
</thead>
    <tbody> 
      <% @meditations.each do |meditation| %>
      
      <tr>
        <th><%= link_to meditation.mood, meditation_path(meditation.id)%></th>
        <th><%= meditation.user.username %></th>
        <th><%= meditation.duration %></th>
        <th><%= meditation.technique.name %></th>

      </tr> 
      <% end %>  
<%= form_tag('/meditations', method: :get, class: "field has-addons") do %>
    <%= text_field_tag(:q, params[:q], class: "input", placeholder: "Search for a") %>
    <%= submit_tag("Search", class: "button is-info") %>
    <% end %>


      
     </tbody>
</table> 

app/views/meditations/new.html.erb
<h1>Create A New Meditation</h1>
<%= render 'form'%>

app/views/meditations/show.html.erb
<h2> <%= @meditation.mood %></h2>


<strong> Duration: </strong>
<%= @meditation.duration %>


<p>
<strong> Mood: </strong> 
<%= @meditation.mood %>
</p>

<p><strong> Technique Name: </strong><%= @meditation.technique.name %> </p>
<p><strong> Technique Description: </strong><%= @meditation.technique.description %> </p>
<br>
<h4><%= link_to 'See All Reviews', meditation_reviews_path(@meditation)%></h4>
<h4><%=link_to "Add A Review", new_meditation_review_path(@meditation)%> </h4>
<br>
<h4>By: <%=link_to @meditation.user.username, user_path(@meditation.user)%> </h4>
<%= link_to 'Edit', edit_meditation_path(@meditation) %> |
<%= link_to 'Delete', meditation_path(@meditation),method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>

 <br>
<%= link_to 'Back', meditations_path %>

app/views/reviews/index.html.erb
<% if @meditation %>
  <h3>Reviews for <%= @meditation.mood%> - <%= @meditation.technique_name %> </h3>
<% else %>
  <h1>All the Reviews </h1>
<% end %>

<ul>
<% @reviews.each do |review| %>

  <li>
    <%= review.meditation.mood%>: <%= link_to review.title, review_path(review)%>
    <br>
   By: <%= review.user.username %>
  </li> <br>

<% end %>
</ul>

app/views/reviews/new.html.erb
<%=  display_header(@review)%>

<%= render partial: 'layouts/errors', locals: {object: @review} %>


<%= form_for(@review) do |f|%>
  <% if params[:meditation_id] %>
    <%= f.hidden_field :meditation_id %>
  <% else %>
    <div>
      <%= f.label :meditation_id, "Select a Meditation" %>
      <br>
    <%= f.collection_select :meditation_id, Meditation.alpha, :id, :mood_and_technique, include_blank: true %>
    </div>
  <% end %>
  <div>
    <%= f.label :stars %>
    <%= f.number_field :stars, min:0, max:5 %>
  </div>
  <br>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
   <br>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content, size: "25x10" %>
  </div>
  
  <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<p><h4>Title:</h4><%= @review.title%></p>
<p><h4>Stars:</h4><%= @review.stars%></p>

<p><h4>Review:</h4> <%= @review.content%> </p>

app/views/techniques/index.html.erb
<div class = "title-container"> 
<h1> All Techniques </h1>
</div>
<div class = "techniques">
<ol type =1>
<% @techniques.each do |technique| %>
<div class = "technique">

<li><spun style="color:blue;"><%= technique.name %></spun> - <%= technique.description %></li>
<br>
</div>
<% end %>

</ol>
</div>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render partial: 'layouts/errors', locals: {object: @user} %>


<%= form_for(@user) do |f|%>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.submit "Sign Up"%>
<% end %>

app/views/users/show.html.erb
<div class "title-container">
<h1> Welcome <%= "#{@user.username}" %></h1> 
</div><p><u>Created Meditations:</u></p>
 <ol type =1 >
  <% @user.meditations.each do |meditation|%>
  <li> <%= link_to meditation.mood, meditation_path(meditation)%> - <%= meditation.technique.name %></li>
  <% end %>
  </ol>
</div>

</div><p><u>Reviewed Meditations:</u></p>
<ol type =2 >
  <% @user.reviewed_meditations.each do |meditation|%>
  <li> <%= link_to meditation.mood, meditation_path(meditation)%> - <%= meditation.technique.name %></li>
  <% end %>
  </ol>
</div>